#pragma once

#define APP_PRODUCT_VERSION_MAJOR 1
#define APP_PRODUCT_VERSION_MINOR 0
#define APP_PRODUCT_VERSION_PATCH 0
#define APP_PRODUCT_VERSION_BUILD 0
#define APP_PRODUCT_VERSION_STRING "1.0.0.0"

#define APP_FILE_VERSION_MAJOR 1
#define APP_FILE_VERSION_MINOR 0
#define APP_FILE_VERSION_PATCH 2
#define APP_FILE_VERSION_BUILD 18
#define APP_FILE_VERSION_STRING "1.0.2.18"
#define APP_FILE_VERSION_WSTRING L"1.0.2.18"

